<!-- GENERATED BY:  Lectora Online v 4.0.0(78) (http://www.trivantis.com) -->
<!-- TITLE: (Shared) LFS201 - Essentials of Linux System Administration -->



var trivstrYA = 'Your answer:'
var trivstrCA = 'Correct answer:'
var trivstrNA = 'Not answered'
var trivstrQ = 'Question '
var trivstrGoToQ = 'Go To Question'
var trivstrFAIL = 'FAILED'
var trivstrPASS = 'PASSED'
var trivstrNG = 'Not Graded'
var trivstrSCORE = 'SCORE:'
var trivstrSTUD = 'Student:'
var trivstrTRSUB = 'Your test results have been submitted.'
var trivstrSUSUB = 'Your survey responses have been submitted.'
var trivstrOK = 'OK'
var trivstrCancel = 'Cancel'
var trivstrPrint = 'Print'
var trivstrDetails = 'Details'
var trivstrCMTO = 'Your session has timed out. Please login again.'
var trivstrERRNQ = 'The number of questions in the test has changed. Please contact your instructor to reset the test results.'
var trivstrERRAS = 'You have already submitted the results of this test.'
var trivstrERRLI = 'You must be properly logged in to CourseMill to submit this test.'
var trivstrERRST = 'There was an error submitting your test results, please try again later.'
var trivstrERRAICC = 'Unable to contact AICC Course Management System.This course must be run from within an AICC Course Management System for the course data to be recorded.'
var trivstrERRIO = 'I/O Error, cannot send results:'
var trivstrERRMU = 'MalformedURL Exception! '
var trivstrERRSE = 'Security Error, unable to send request.This course must be loaded from the system that the data is submitted to:'
var trivstrERRUH = 'Unable to find local host, cannot send results:'
var trivstrCOR = 'Correct'
var trivstrINC = 'Incorrect'
var trivstrLKP = 'Link to question'
var trivstrLKF = 'Link to first page in test'
var trivstrCOVT = 'Correct-over-total count:'
var trivstrFBTR = 'Feedback:'
var trivstrPSCO = 'Lowest passing score:'
var trivstrSEL = 'Selected'
var trivstrNOSEL = 'Not selected'
var trivstrBGNCR = 'Tap here to begin the course.'
var trivstrRMDROPS = 'The drag item limit for this question is ##0 in each drop zone. Remove an item to change entries.'
var trivstrUpdate = 'Update';
var trivstrRefresh = 'Refresh';
var trivstrClose = 'Close';
var trivstrVariables = 'Variables';
var trivstrClear = 'Clear';
var trivstrErrLoadTestServer = 'You must run this content from a web-based server [##0]: ##1';
var trivstrErrLoadTestXml = 'Unable to process test [##0] because of an XML parse error.';
var trivstrPopBlock = 'Please disable any popup blockers.';
var trivstrAnd = 'and';
var trivstrOr = 'or';
